### ISSUE TITLE
Turns - phases - rounds?

### ISSUE THREAD

**Issue by smugleafdev** [BlueShiftDevs/Blueshift#3]

**Comment by FarCryFromHuman** [comment]
@HphWayuo mentioned using "cycle" as a term since it matches thematically.

**Comment by FarCryFromHuman** [comment]
We've settled on Cycle for the entire round structure and Phase for the discrete segments of a Cycle. There is the concept of players "taking turns" while in the Action and Deployment phases, but this just means alternating plays.

Closing the issue.
