### ISSUE TITLE
VP and fleet IDs

### ISSUE THREAD

**Issue by smugleafdev** [BlueShiftDevs/Blueshift#5]
There may be an issue with VP rate gain between IDs as well as certain IDs being blocked from every reaching the maximum.

Example, one fleet could gain VP for exploration and exhausting. These are finite resources. Another fleet could gain VP at the end of every turn for controlling more locations. This is an infinite resource of points, but also much slower than the other fleet.

**Comment by FarCryFromHuman** [comment]
We've decided to have both unlimited and limited VP gain abilities on fleets. Unlimited will be balanced by difficult conditions and/or low yield, and limited will typically have higher yield and/or easier conditions.
